#!/bin/bash
set -euo pipefail

# ==============================
# IMPORT KEY VARIABLES
# ==============================
set -a
source ../hwrf_run.config
set +a

cd $coupled_run_path
# ==============================

ln -sf $iola_repo_path/sorc/WRFV3/main/wrf.exe .

ln -sf $fix_path/hwrf_eta_micro_lookup.dat eta_micro_lookup.dat
ln -sf $fix_path/hwrf_track track
ln -sf $fix_path/hwrf-wrf/RRTMG_LW_DATA RRTMG_LW_DATA
ln -sf $fix_path/hwrf-wrf/CAM_AEROPT_DATA CAM_AEROPT_DATA
ln -sf $fix_path/hwrf-wrf/ozone_plev.formatted ozone_plev.formatted
ln -sf $fix_path/hwrf-wrf/coeff_q.asc coeff_q.asc
ln -sf $fix_path/hwrf-wrf/LANDUSE.TBL LANDUSE.TBL
ln -sf $fix_path/hwrf-wrf/aerosol.formatted aerosol.formatted
ln -sf $fix_path/hwrf-wrf/CLM_EXT_ICE_DFS_DATA CLM_EXT_ICE_DFS_DATA
ln -sf $fix_path/hwrf-wrf/kernels.asc_s_0_03_0_9 kernels.asc_s_0_03_0_9
ln -sf $fix_path/hwrf-wrf/grib2map.tbl grib2map.tbl
ln -sf $fix_path/hwrf-wrf/CLM_DRDSDT0_DATA CLM_DRDSDT0_DATA
ln -sf $fix_path/hwrf-wrf/wind-turbine-1.tbl wind-turbine-1.tbl
ln -sf $fix_path/hwrf-wrf/CLM_ALB_ICE_DRC_DATA CLM_ALB_ICE_DRC_DATA
ln -sf $fix_path/hwrf-wrf/GENPARM.TBL GENPARM.TBL
ln -sf $fix_path/hwrf-wrf/RRTM_DATA_DBL RRTM_DATA_DBL
ln -sf $fix_path/hwrf-wrf/README.namelist README.namelist
ln -sf $fix_path/hwrf-wrf/kernels_z.asc kernels_z.asc
ln -sf $fix_path/hwrf-wrf/gribmap.txt gribmap.txt
ln -sf $fix_path/hwrf-wrf/tr49t85 tr49t85
ln -sf $fix_path/hwrf-wrf/tr49t67 tr49t67
ln -sf $fix_path/hwrf-wrf/CLM_ASM_ICE_DRC_DATA CLM_ASM_ICE_DRC_DATA
ln -sf $fix_path/hwrf-wrf/constants.asc constants.asc
ln -sf $fix_path/hwrf-wrf/ETAMPNEW_DATA_DBL ETAMPNEW_DATA_DBL
ln -sf $fix_path/hwrf-wrf/aerosol_plev.formatted aerosol_plev.formatted
ln -sf $fix_path/hwrf-wrf/RRTMG_SW_DATA RRTMG_SW_DATA
ln -sf $fix_path/hwrf-wrf/ozone.formatted ozone.formatted
ln -sf $fix_path/hwrf-wrf/aerosol_lon.formatted aerosol_lon.formatted
ln -sf $fix_path/hwrf-wrf/tr67t85 tr67t85
ln -sf $fix_path/hwrf-wrf/RRTMG_SW_DATA_DBL RRTMG_SW_DATA_DBL
ln -sf $fix_path/hwrf-wrf/co2_trans co2_trans
ln -sf $fix_path/hwrf-wrf/URBPARM_UZE.TBL URBPARM_UZE.TBL
ln -sf $fix_path/hwrf-wrf/CLM_ALB_ICE_DFS_DATA CLM_ALB_ICE_DFS_DATA
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.RCP6 CAMtr_volume_mixing_ratio.RCP6
ln -sf $fix_path/hwrf-wrf/RRTMG_LW_DATA_DBL RRTMG_LW_DATA_DBL
ln -sf $fix_path/hwrf-wrf/CLM_ASM_ICE_DFS_DATA CLM_ASM_ICE_DFS_DATA
ln -sf $fix_path/hwrf-wrf/coeff_p.asc coeff_p.asc
ln -sf $fix_path/hwrf-wrf/CLM_KAPPA_DATA CLM_KAPPA_DATA
ln -sf $fix_path/hwrf-wrf/bulkradii.asc_s_0_03_0_9 bulkradii.asc_s_0_03_0_9
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.A1B CAMtr_volume_mixing_ratio.A1B
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.A2 CAMtr_volume_mixing_ratio.A2
ln -sf $fix_path/hwrf-wrf/ozone_lat.formatted ozone_lat.formatted
ln -sf $fix_path/hwrf-wrf/aerosol_lat.formatted aerosol_lat.formatted
ln -sf $fix_path/hwrf-wrf/ETAMPNEW_DATA ETAMPNEW_DATA
ln -sf $fix_path/hwrf-wrf/CLM_EXT_ICE_DRC_DATA CLM_EXT_ICE_DRC_DATA
ln -sf $fix_path/hwrf-wrf/termvels.asc termvels.asc
ln -sf $fix_path/hwrf-wrf/README.tslist README.tslist
ln -sf $fix_path/hwrf-wrf/bulkdens.asc_s_0_03_0_9 bulkdens.asc_s_0_03_0_9
ln -sf $fix_path/hwrf-wrf/RRTM_DATA
ln -sf $fix_path/hwrf-wrf/ETAMPNEW_DATA.expanded_rain ETAMPNEW_DATA.expanded_rain
ln -sf $fix_path/hwrf-wrf/CLM_TAU_DATA CLM_TAU_DATA
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.RCP8.5 CAMtr_volume_mixing_ratio.RCP8.5
ln -sf $fix_path/hwrf-wrf/CCN_ACTIVATE.BIN CCN_ACTIVATE.BIN
ln -sf $fix_path/hwrf-wrf/URBPARM.TBL URBPARM.TBL
ln -sf $fix_path/hwrf-wrf/capacity.asc capacity.asc
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.RCP4.5 CAMtr_volume_mixing_ratio.RCP4.5
ln -sf $fix_path/hwrf-wrf/masses.asc masses.asc
ln -sf $fix_path/hwrf-wrf/CAM_ABS_DATA CAM_ABS_DATA
ln -sf $fix_path/hwrf-wrf/ETAMPNEW_DATA.expanded_rain_DBL ETAMPNEW_DATA.expanded_rain_DBL
ln -sf $fix_path/hwrf-wrf/SOILPARM.TBL SOILPARM.TBL
ln -sf $fix_path/hwrf-wrf/VEGPARM.TBL VEGPARM.TBL
ln -sf $fix_path/hwrf-wrf/MPTABLE.TBL MPTABLE.TBL

cp $wrf_init/namelist.input .
cp $wrf_init/geo_nmm* .
cp $wrf_init/wrfinput_d01 .
cp $wrf_init/wrfbdy_d01 .
cp $wrf_init/fort.65 .

ln -sf $iola_repo_path/sorc/ncep-coupler/cpl_exec/hwrf_wm3c.exe .

cat > cpl_nml << 'EOF'
 &CPL_SETTINGS
COOR_R8 = T
restart = F
cstepmax = 560
dt_c = 360
INTP_INI_STUCK_OK = T
VerbLev = 1
ia2o = 1
io2a = 1
ia2w = 1
iw2a = 0
io2w = 0
iw2o = 0
/
EOF
