#!/bin/bash
set -euo pipefail

# ==============================
# IMPORT KEY VARIABLES
# ==============================
set -a
source ../hwrf_run.config
set +a

mkdir -p $wrf_init
cd $wrf_init
# ==============================

ln -fs $iola_repo_path/sorc/WPSV3/geogrid.exe .
ln -sf $iola_repo_path/parm/hwrf_GEOGRID.TBL ./GEOGRID.TBL
ln -sf $iola_repo_path/parm/hwrf_METGRID.TBL ./METGRID.TBL

ln -fs $iola_repo_path/parm/hwrf_Vtable_gfs2017 ./Vtable
ln -fs $iola_repo_path/sorc/WPSV3/ungrib.exe .
ln -fs $iola_repo_path/sorc/WPSV3/metgrid.exe .

ln -fs $iola_repo_path/sorc/WRFV3/main/real_nmm.exe .
ln -fs $iola_repo_path/sorc/WRFV3/main/wrf.exe .

ln -sf $fix_path/hwrf_eta_micro_lookup.dat eta_micro_lookup.dat
ln -sf $fix_path/hwrf_track track
ln -sf $fix_path/hwrf-wrf/RRTMG_LW_DATA RRTMG_LW_DATA
ln -sf $fix_path/hwrf-wrf/CAM_AEROPT_DATA CAM_AEROPT_DATA
ln -sf $fix_path/hwrf-wrf/ozone_plev.formatted ozone_plev.formatted
ln -sf $fix_path/hwrf-wrf/coeff_q.asc coeff_q.asc
ln -sf $fix_path/hwrf-wrf/LANDUSE.TBL LANDUSE.TBL
ln -sf $fix_path/hwrf-wrf/aerosol.formatted aerosol.formatted
ln -sf $fix_path/hwrf-wrf/CLM_EXT_ICE_DFS_DATA CLM_EXT_ICE_DFS_DATA
ln -sf $fix_path/hwrf-wrf/kernels.asc_s_0_03_0_9 kernels.asc_s_0_03_0_9
ln -sf $fix_path/hwrf-wrf/grib2map.tbl grib2map.tbl
ln -sf $fix_path/hwrf-wrf/CLM_DRDSDT0_DATA CLM_DRDSDT0_DATA
ln -sf $fix_path/hwrf-wrf/wind-turbine-1.tbl wind-turbine-1.tbl
ln -sf $fix_path/hwrf-wrf/CLM_ALB_ICE_DRC_DATA CLM_ALB_ICE_DRC_DATA
ln -sf $fix_path/hwrf-wrf/GENPARM.TBL GENPARM.TBL
ln -sf $fix_path/hwrf-wrf/RRTM_DATA_DBL RRTM_DATA_DBL
ln -sf $fix_path/hwrf-wrf/README.namelist README.namelist
ln -sf $fix_path/hwrf-wrf/kernels_z.asc kernels_z.asc
ln -sf $fix_path/hwrf-wrf/gribmap.txt gribmap.txt
ln -sf $fix_path/hwrf-wrf/tr49t85 tr49t85
ln -sf $fix_path/hwrf-wrf/tr49t67 tr49t67
ln -sf $fix_path/hwrf-wrf/CLM_ASM_ICE_DRC_DATA CLM_ASM_ICE_DRC_DATA
ln -sf $fix_path/hwrf-wrf/constants.asc constants.asc
ln -sf $fix_path/hwrf-wrf/ETAMPNEW_DATA_DBL ETAMPNEW_DATA_DBL
ln -sf $fix_path/hwrf-wrf/aerosol_plev.formatted aerosol_plev.formatted
ln -sf $fix_path/hwrf-wrf/RRTMG_SW_DATA RRTMG_SW_DATA
ln -sf $fix_path/hwrf-wrf/ozone.formatted ozone.formatted
ln -sf $fix_path/hwrf-wrf/aerosol_lon.formatted aerosol_lon.formatted
ln -sf $fix_path/hwrf-wrf/tr67t85 tr67t85
ln -sf $fix_path/hwrf-wrf/RRTMG_SW_DATA_DBL RRTMG_SW_DATA_DBL
ln -sf $fix_path/hwrf-wrf/co2_trans co2_trans
ln -sf $fix_path/hwrf-wrf/URBPARM_UZE.TBL URBPARM_UZE.TBL
ln -sf $fix_path/hwrf-wrf/CLM_ALB_ICE_DFS_DATA CLM_ALB_ICE_DFS_DATA
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.RCP6 CAMtr_volume_mixing_ratio.RCP6
ln -sf $fix_path/hwrf-wrf/RRTMG_LW_DATA_DBL RRTMG_LW_DATA_DBL
ln -sf $fix_path/hwrf-wrf/CLM_ASM_ICE_DFS_DATA CLM_ASM_ICE_DFS_DATA
ln -sf $fix_path/hwrf-wrf/coeff_p.asc coeff_p.asc
ln -sf $fix_path/hwrf-wrf/CLM_KAPPA_DATA CLM_KAPPA_DATA
ln -sf $fix_path/hwrf-wrf/bulkradii.asc_s_0_03_0_9 bulkradii.asc_s_0_03_0_9
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.A1B CAMtr_volume_mixing_ratio.A1B
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.A2 CAMtr_volume_mixing_ratio.A2
ln -sf $fix_path/hwrf-wrf/ozone_lat.formatted ozone_lat.formatted
ln -sf $fix_path/hwrf-wrf/aerosol_lat.formatted aerosol_lat.formatted
ln -sf $fix_path/hwrf-wrf/ETAMPNEW_DATA ETAMPNEW_DATA
ln -sf $fix_path/hwrf-wrf/CLM_EXT_ICE_DRC_DATA CLM_EXT_ICE_DRC_DATA
ln -sf $fix_path/hwrf-wrf/termvels.asc termvels.asc
ln -sf $fix_path/hwrf-wrf/README.tslist README.tslist
ln -sf $fix_path/hwrf-wrf/bulkdens.asc_s_0_03_0_9 bulkdens.asc_s_0_03_0_9
ln -sf $fix_path/hwrf-wrf/RRTM_DATA
ln -sf $fix_path/hwrf-wrf/ETAMPNEW_DATA.expanded_rain ETAMPNEW_DATA.expanded_rain
ln -sf $fix_path/hwrf-wrf/CLM_TAU_DATA CLM_TAU_DATA
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.RCP8.5 CAMtr_volume_mixing_ratio.RCP8.5
ln -sf $fix_path/hwrf-wrf/CCN_ACTIVATE.BIN CCN_ACTIVATE.BIN
ln -sf $fix_path/hwrf-wrf/URBPARM.TBL URBPARM.TBL
ln -sf $fix_path/hwrf-wrf/capacity.asc capacity.asc
ln -sf $fix_path/hwrf-wrf/CAMtr_volume_mixing_ratio.RCP4.5 CAMtr_volume_mixing_ratio.RCP4.5
ln -sf $fix_path/hwrf-wrf/masses.asc masses.asc
ln -sf $fix_path/hwrf-wrf/CAM_ABS_DATA CAM_ABS_DATA
ln -sf $fix_path/hwrf-wrf/ETAMPNEW_DATA.expanded_rain_DBL ETAMPNEW_DATA.expanded_rain_DBL
ln -sf $fix_path/hwrf-wrf/SOILPARM.TBL SOILPARM.TBL
ln -sf $fix_path/hwrf-wrf/VEGPARM.TBL VEGPARM.TBL
ln -sf $fix_path/hwrf-wrf/MPTABLE.TBL MPTABLE.TBL
ln -sf $fix_path/hwrf_wps_geo geog-data

$iola_repo_path/sorc/WPSV3/link_grib.csh $input_data_path/gfs/gfs.$cycle/gfs*

cp $iola_repo_path/iola-utilities/create_namelist.py .
new_coords_dir="${iola_repo_path}/parm/iola"
sed -i \
    "s|^coords_dir *= *'.*'|coords_dir='${iola_repo_path}/parm/iola'|" \
    "create_namelist.py"

# Parse cycle
YYYY=${cycle:0:4}
MM=${cycle:4:2}
DD=${cycle:6:2}
HH=${cycle:8:2}

# Compute start and end dates
start_date=$(date -u -d "${YYYY}-${MM}-${DD} ${HH}:00:00" "+%Y-%m-%d %H:%M:%S")
end_date=$(date -u -d "${start_date} ${forecast_length} hours" "+%Y-%m-%d %H:%M:%S")

# Replace lines
sed -i \
  -e "s|^start_date *=.*|start_date=\"${start_date}\"|" \
  -e "s|^end_date *=.*|end_date=\"${end_date}\"|" \
  "create_namelist.py"
