PATH_TO_NWJET=../../nwjet
include ../../nwjet/sorc/config/configure.hwrf

OBJS	= select_domain.o
EXEC	= hwrf_select_domain

$(EXEC):	$(OBJS)
	$(SFC) $(LDFLAGS) -o $@ $(OBJS)

.PHONY: clean

clean:
	$(RM) $(OBJS) $(EXEC)

